# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sari.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1245, 797)
        MainWindow.setStyleSheet("font: 9pt \"Segoe UI\";background-color:rgb(39, 40, 34)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 720))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graph_tab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.graph_tab.setFont(font)
        self.graph_tab.setAutoFillBackground(False)
        self.graph_tab.setStyleSheet("font: 9pt \"Segoe UI\";background-color:rgb(39, 40, 34)")
        self.graph_tab.setObjectName("graph_tab")
        self.real_time_tab = QtWidgets.QWidget()
        self.real_time_tab.setObjectName("real_time_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.real_time_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box_rtc_gsr = QtWidgets.QGroupBox(self.real_time_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_box_rtc_gsr.sizePolicy().hasHeightForWidth())
        self.group_box_rtc_gsr.setSizePolicy(sizePolicy)
        self.group_box_rtc_gsr.setMinimumSize(QtCore.QSize(910, 210))
        self.group_box_rtc_gsr.setStyleSheet("color:white")
        self.group_box_rtc_gsr.setObjectName("group_box_rtc_gsr")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_box_rtc_gsr)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rtc_graph_gsr = pg.PlotWidget(self.group_box_rtc_gsr)
        self.rtc_graph_gsr.setBackground("#272822")
        self.rtc_graph_gsr.setObjectName("rtc_graph_gsr")
        self.gridLayout_3.addWidget(self.rtc_graph_gsr, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.group_box_rtc_gsr)
        self.group_box_rtc_hr_interval = QtWidgets.QGroupBox(self.real_time_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_box_rtc_hr_interval.sizePolicy().hasHeightForWidth())
        self.group_box_rtc_hr_interval.setSizePolicy(sizePolicy)
        self.group_box_rtc_hr_interval.setMinimumSize(QtCore.QSize(910, 210))
        self.group_box_rtc_hr_interval.setStyleSheet("color:white")
        self.group_box_rtc_hr_interval.setObjectName("group_box_rtc_hr_interval")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_box_rtc_hr_interval)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rtc_graph_interval = pg.PlotWidget(self.group_box_rtc_hr_interval)
        self.rtc_graph_interval.setBackground("#272822")
        self.rtc_graph_interval.setObjectName("rtc_graph_interval")
        self.gridLayout_4.addWidget(self.rtc_graph_interval, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.group_box_rtc_hr_interval)
        self.group_box_rtc_hrv = QtWidgets.QGroupBox(self.real_time_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_box_rtc_hrv.sizePolicy().hasHeightForWidth())
        self.group_box_rtc_hrv.setSizePolicy(sizePolicy)
        self.group_box_rtc_hrv.setMinimumSize(QtCore.QSize(910, 210))
        self.group_box_rtc_hrv.setStyleSheet("color:white")
        self.group_box_rtc_hrv.setObjectName("group_box_rtc_hrv")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_box_rtc_hrv)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rtc_graph_hrv = pg.PlotWidget(self.group_box_rtc_hrv)
        self.rtc_graph_hrv.setBackground("#272822")
        self.rtc_graph_hrv.setObjectName("rtc_graph_hrv")
        self.gridLayout_5.addWidget(self.rtc_graph_hrv, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.group_box_rtc_hrv)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.graph_tab.addTab(self.real_time_tab, "")
        self.full_time_tab = QtWidgets.QWidget()
        self.full_time_tab.setObjectName("full_time_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.full_time_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.full_time_tab)
        self.stackedWidget.setMinimumSize(QtCore.QSize(940, 670))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_gsr = QtWidgets.QWidget()
        self.page_gsr.setObjectName("page_gsr")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_gsr)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.full_graph_gsr = pg.PlotWidget(self.page_gsr)
        self.full_graph_gsr.setMinimumSize(QtCore.QSize(900, 566))
        self.full_graph_gsr.setObjectName("full_graph_gsr")
        self.full_graph_gsr.setBackground("#272822")
        self.gridLayout_7.addWidget(self.full_graph_gsr, 2, 0, 1, 2)
        self.full_time_gsr_label = QtWidgets.QLabel(self.page_gsr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.full_time_gsr_label.sizePolicy().hasHeightForWidth())
        self.full_time_gsr_label.setSizePolicy(sizePolicy)
        self.full_time_gsr_label.setStyleSheet("color:white;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.full_time_gsr_label.setObjectName("full_time_gsr_label")
        self.gridLayout_7.addWidget(self.full_time_gsr_label, 0, 0, 1, 1)
        self.next_gsr = QtWidgets.QPushButton(self.page_gsr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_gsr.sizePolicy().hasHeightForWidth())
        self.next_gsr.setSizePolicy(sizePolicy)
        self.next_gsr.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.next_gsr.setFlat(True)
        self.next_gsr.setObjectName("next_gsr")
        self.gridLayout_7.addWidget(self.next_gsr, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_gsr)
        self.page_interval = QtWidgets.QWidget()
        self.page_interval.setObjectName("page_interval")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_interval)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.full_time_interval_label = QtWidgets.QLabel(self.page_interval)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.full_time_interval_label.sizePolicy().hasHeightForWidth())
        self.full_time_interval_label.setSizePolicy(sizePolicy)
        self.full_time_interval_label.setStyleSheet("color:white;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.full_time_interval_label.setObjectName("full_time_interval_label")
        self.gridLayout_9.addWidget(self.full_time_interval_label, 0, 0, 1, 1)
        self.full_graph_interval = pg.PlotWidget(self.page_interval)
        self.full_graph_interval.setMinimumSize(QtCore.QSize(900, 566))
        self.full_graph_interval.setObjectName("full_graph_interval")
        self.full_graph_interval.setBackground("#272822")
        self.gridLayout_9.addWidget(self.full_graph_interval, 1, 0, 1, 1)
        self.next_interval = QtWidgets.QPushButton(self.page_interval)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_interval.sizePolicy().hasHeightForWidth())
        self.next_interval.setSizePolicy(sizePolicy)
        self.next_interval.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.next_interval.setFlat(True)
        self.next_interval.setObjectName("next_interval")
        self.gridLayout_9.addWidget(self.next_interval, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_interval)
        self.page_hrv = QtWidgets.QWidget()
        self.page_hrv.setObjectName("page_hrv")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_hrv)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.full_time_hrv = QtWidgets.QLabel(self.page_hrv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.full_time_hrv.sizePolicy().hasHeightForWidth())
        self.full_time_hrv.setSizePolicy(sizePolicy)
        self.full_time_hrv.setStyleSheet("color:white;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.full_time_hrv.setObjectName("full_time_hrv")
        self.gridLayout_10.addWidget(self.full_time_hrv, 0, 0, 1, 1)
        self.full_graph_hrv = pg.PlotWidget(self.page_hrv)
        self.full_graph_hrv.setMinimumSize(QtCore.QSize(900, 566))
        self.full_graph_hrv.setObjectName("full_graph_hrv")
        self.full_graph_hrv.setBackground("#272822")
        self.gridLayout_10.addWidget(self.full_graph_hrv, 1, 0, 1, 1)
        self.next_hrv = QtWidgets.QPushButton(self.page_hrv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_hrv.sizePolicy().hasHeightForWidth())
        self.next_hrv.setSizePolicy(sizePolicy)
        self.next_hrv.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.next_hrv.setFlat(True)
        self.next_hrv.setObjectName("next_hrv")
        self.gridLayout_10.addWidget(self.next_hrv, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_hrv)
        self.gridLayout_8.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.graph_tab.addTab(self.full_time_tab, "")
        self.partition_tab = QtWidgets.QWidget()
        self.partition_tab.setObjectName("partition_tab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.partition_tab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.stackedWidget_partition = QtWidgets.QStackedWidget(self.partition_tab)
        self.stackedWidget_partition.setMinimumSize(QtCore.QSize(940, 670))
        self.stackedWidget_partition.setObjectName("stackedWidget_partition")
        self.page_video_1 = QtWidgets.QWidget()
        self.page_video_1.setObjectName("page_video_1")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_video_1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_video_1 = QtWidgets.QLabel(self.page_video_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_video_1.sizePolicy().hasHeightForWidth())
        self.label_video_1.setSizePolicy(sizePolicy)
        self.label_video_1.setStyleSheet("color:white;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_video_1.setObjectName("label_video_1")
        self.gridLayout_14.addWidget(self.label_video_1, 0, 0, 1, 1)
        self.graph_video_1 = pg.PlotWidget(self.page_video_1)
        self.graph_video_1.setMinimumSize(QtCore.QSize(900, 566))
        self.graph_video_1.setObjectName("graph_video_1")
        self.graph_video_1.setBackground("#272822")
        self.gridLayout_14.addWidget(self.graph_video_1, 1, 0, 1, 1)
        self.next_video_1 = QtWidgets.QPushButton(self.page_video_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_video_1.sizePolicy().hasHeightForWidth())
        self.next_video_1.setSizePolicy(sizePolicy)
        self.next_video_1.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.next_video_1.setFlat(True)
        self.next_video_1.setObjectName("next_video_1")
        self.gridLayout_14.addWidget(self.next_video_1, 2, 0, 1, 1)
        self.stackedWidget_partition.addWidget(self.page_video_1)
        self.page_video_2 = QtWidgets.QWidget()
        self.page_video_2.setObjectName("page_video_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_video_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_video_2 = QtWidgets.QLabel(self.page_video_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_video_2.sizePolicy().hasHeightForWidth())
        self.label_video_2.setSizePolicy(sizePolicy)
        self.label_video_2.setStyleSheet("color:white;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_video_2.setObjectName("label_video_2")
        self.gridLayout_15.addWidget(self.label_video_2, 0, 0, 1, 1)
        self.graph_video_2 = pg.PlotWidget(self.page_video_2)
        self.graph_video_2.setMinimumSize(QtCore.QSize(900, 566))
        self.graph_video_2.setObjectName("graph_video_2")
        self.graph_video_2.setBackground("#272822")
        self.gridLayout_15.addWidget(self.graph_video_2, 1, 0, 1, 1)
        self.next_video_2 = QtWidgets.QPushButton(self.page_video_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_video_2.sizePolicy().hasHeightForWidth())
        self.next_video_2.setSizePolicy(sizePolicy)
        self.next_video_2.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.next_video_2.setFlat(True)
        self.next_video_2.setObjectName("next_video_2")
        self.gridLayout_15.addWidget(self.next_video_2, 2, 0, 1, 1)
        self.stackedWidget_partition.addWidget(self.page_video_2)
        self.page_video_3 = QtWidgets.QWidget()
        self.page_video_3.setObjectName("page_video_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_video_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_video_3 = QtWidgets.QLabel(self.page_video_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_video_3.sizePolicy().hasHeightForWidth())
        self.label_video_3.setSizePolicy(sizePolicy)
        self.label_video_3.setStyleSheet("color:white;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_video_3.setObjectName("label_video_3")
        self.gridLayout_16.addWidget(self.label_video_3, 0, 0, 1, 1)
        self.graph_video_3 = pg.PlotWidget(self.page_video_3)
        self.graph_video_3.setMinimumSize(QtCore.QSize(900, 566))
        self.graph_video_3.setObjectName("graph_video_3")
        self.graph_video_3.setBackground("#272822")
        self.gridLayout_16.addWidget(self.graph_video_3, 1, 0, 1, 1)
        self.next_video_3 = QtWidgets.QPushButton(self.page_video_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_video_3.sizePolicy().hasHeightForWidth())
        self.next_video_3.setSizePolicy(sizePolicy)
        self.next_video_3.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.next_video_3.setFlat(True)
        self.next_video_3.setObjectName("next_video_3")
        self.gridLayout_16.addWidget(self.next_video_3, 2, 0, 1, 1)
        self.stackedWidget_partition.addWidget(self.page_video_3)
        self.page_video_4 = QtWidgets.QWidget()
        self.page_video_4.setObjectName("page_video_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page_video_4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_video_4 = QtWidgets.QLabel(self.page_video_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_video_4.sizePolicy().hasHeightForWidth())
        self.label_video_4.setSizePolicy(sizePolicy)
        self.label_video_4.setStyleSheet("color:white;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_video_4.setObjectName("label_video_4")
        self.gridLayout_18.addWidget(self.label_video_4, 0, 0, 1, 1)
        self.graph_video_4 = pg.PlotWidget(self.page_video_4)
        self.graph_video_4.setMinimumSize(QtCore.QSize(900, 566))
        self.graph_video_4.setObjectName("graph_video_4")
        self.graph_video_4.setBackground("#272822")
        self.gridLayout_18.addWidget(self.graph_video_4, 1, 0, 1, 1)
        self.next_video_4 = QtWidgets.QPushButton(self.page_video_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_video_4.sizePolicy().hasHeightForWidth())
        self.next_video_4.setSizePolicy(sizePolicy)
        self.next_video_4.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.next_video_4.setFlat(True)
        self.next_video_4.setObjectName("next_video_4")
        self.gridLayout_18.addWidget(self.next_video_4, 2, 0, 1, 1)
        self.stackedWidget_partition.addWidget(self.page_video_4)
        self.gridLayout_17.addWidget(self.stackedWidget_partition, 0, 0, 1, 1)
        self.graph_tab.addTab(self.partition_tab, "")
        self.gridLayout.addWidget(self.graph_tab, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox.setStyleSheet("background-color:rgb(60,63,65);color:white")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_rtc = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rtc.sizePolicy().hasHeightForWidth())
        self.label_rtc.setSizePolicy(sizePolicy)
        self.label_rtc.setMinimumSize(QtCore.QSize(230, 20))
        self.label_rtc.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_rtc.setObjectName("label_rtc")
        self.gridLayout_6.addWidget(self.label_rtc, 0, 0, 1, 2)
        self.group_box_value = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_box_value.sizePolicy().hasHeightForWidth())
        self.group_box_value.setSizePolicy(sizePolicy)
        self.group_box_value.setMinimumSize(QtCore.QSize(230, 280))
        self.group_box_value.setMaximumSize(QtCore.QSize(230, 280))
        self.group_box_value.setStyleSheet("background-color:rgb(60,63,65);color:white;border: 2px solid gray;")
        self.group_box_value.setTitle("")
        self.group_box_value.setObjectName("group_box_value")
        self.var_gsr = QtWidgets.QLabel(self.group_box_value)
        self.var_gsr.setGeometry(QtCore.QRect(5, 45, 221, 51))
        self.var_gsr.setStyleSheet("background-color:rgb(60,63,65);color:rgb(247,145,30);border: 0px solid gray;\n"
"font: 75 30pt \"Tahoma\";")
        self.var_gsr.setObjectName("var_gsr")
        self.label_gsr = QtWidgets.QLabel(self.group_box_value)
        self.label_gsr.setGeometry(QtCore.QRect(15, 15, 116, 31))
        self.label_gsr.setStyleSheet("background-color:rgb(60,63,65);color:white;border: 0px solid gray;\n"
"font: 75 12pt \"Tahoma\";")
        self.label_gsr.setObjectName("label_gsr")
        self.label_interval = QtWidgets.QLabel(self.group_box_value)
        self.label_interval.setGeometry(QtCore.QRect(15, 105, 116, 31))
        self.label_interval.setStyleSheet("background-color:rgb(60,63,65);color:white;border: 0px solid gray;\n"
"font: 75 12pt \"Tahoma\";")
        self.label_interval.setObjectName("label_interval")
        self.var_interval = QtWidgets.QLabel(self.group_box_value)
        self.var_interval.setGeometry(QtCore.QRect(5, 130, 221, 51))
        self.var_interval.setStyleSheet("background-color:rgb(60,63,65);color:rgb(247,145,30);border: 0px solid gray;\n"
"font: 75 30pt \"Tahoma\";")
        self.var_interval.setObjectName("var_interval")
        self.label_hrv = QtWidgets.QLabel(self.group_box_value)
        self.label_hrv.setGeometry(QtCore.QRect(15, 190, 116, 31))
        self.label_hrv.setStyleSheet("background-color:rgb(60,63,65);color:white;border: 0px solid gray;\n"
"font: 75 12pt \"Tahoma\";")
        self.label_hrv.setObjectName("label_hrv")
        self.var_hrv = QtWidgets.QLabel(self.group_box_value)
        self.var_hrv.setGeometry(QtCore.QRect(5, 215, 221, 51))
        self.var_hrv.setStyleSheet("background-color:rgb(60,63,65);color:rgb(247,145,30);border: 0px solid gray;\n"
"font: 75 30pt \"Tahoma\";")
        self.var_hrv.setObjectName("var_hrv")
        self.gridLayout_6.addWidget(self.group_box_value, 1, 0, 1, 2)
        self.label_comment = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_comment.sizePolicy().hasHeightForWidth())
        self.label_comment.setSizePolicy(sizePolicy)
        self.label_comment.setMinimumSize(QtCore.QSize(230, 20))
        self.label_comment.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_comment.setObjectName("label_comment")
        self.gridLayout_6.addWidget(self.label_comment, 2, 0, 1, 2)
        self.comment_entry = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_entry.sizePolicy().hasHeightForWidth())
        self.comment_entry.setSizePolicy(sizePolicy)
        self.comment_entry.setMinimumSize(QtCore.QSize(230, 40))
        self.comment_entry.setMaximumSize(QtCore.QSize(230, 40))
        self.comment_entry.setStyleSheet("background-color:rgb(60,63,65);color:white;border: 2px solid gray;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comment_entry.setObjectName("comment_entry")
        self.gridLayout_6.addWidget(self.comment_entry, 3, 0, 1, 2)
        self.label_history = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_history.sizePolicy().hasHeightForWidth())
        self.label_history.setSizePolicy(sizePolicy)
        self.label_history.setMinimumSize(QtCore.QSize(230, 20))
        self.label_history.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_history.setObjectName("label_history")
        self.gridLayout_6.addWidget(self.label_history, 4, 0, 1, 2)
        self.history = QtWidgets.QTextBrowser(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history.sizePolicy().hasHeightForWidth())
        self.history.setSizePolicy(sizePolicy)
        self.history.setMinimumSize(QtCore.QSize(230, 200))
        self.history.setStyleSheet("background-color:rgb(60,63,65);color:white;border: 2px solid gray;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.history.setObjectName("history")
        self.gridLayout_6.addWidget(self.history, 5, 0, 1, 2)
        self.port = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setMinimumSize(QtCore.QSize(130, 35))
        self.port.setMaximumSize(QtCore.QSize(130, 35))
        self.port.setStyleSheet("background-color:rgb(60,63,65);color:white;border: 2px solid gray;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.port.setObjectName("port")
        self.gridLayout_6.addWidget(self.port, 6, 0, 1, 1)
        self.button_start = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start.sizePolicy().hasHeightForWidth())
        self.button_start.setSizePolicy(sizePolicy)
        self.button_start.setMinimumSize(QtCore.QSize(93, 35))
        self.button_start.setStyleSheet("background-color:rgb(91,216,198);color:red\n"
";border: 2px ;font: 75 11pt \"MS Shell Dlg 2\";")
        self.button_start.setFlat(False)
        self.button_start.setObjectName("button_start")
        self.gridLayout_6.addWidget(self.button_start, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1245, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet("font: 10pt \"Segoe UI\";background-color:rgb(39, 40, 34);color:white")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionLoad_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_File.setObjectName("actionLoad_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionLoad_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.graph_tab.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_partition.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BioHumanFeedback"))
        self.group_box_rtc_gsr.setTitle(_translate("MainWindow", "Galvanic Skin Responses"))
        self.group_box_rtc_hr_interval.setTitle(_translate("MainWindow", "Heart Beat Interval"))
        self.group_box_rtc_hrv.setTitle(_translate("MainWindow", "Heart Rate Variability"))
        self.graph_tab.setTabText(self.graph_tab.indexOf(self.real_time_tab), _translate("MainWindow", "Real Time Graph"))
        self.full_time_gsr_label.setText(_translate("MainWindow", "Galvanic Skin Responses"))
        self.next_gsr.setText(_translate("MainWindow", ">>"))
        self.full_time_interval_label.setText(_translate("MainWindow", "Heart Beat Interval"))
        self.next_interval.setText(_translate("MainWindow", ">>"))
        self.full_time_hrv.setText(_translate("MainWindow", "Heart Rate Variability"))
        self.next_hrv.setText(_translate("MainWindow", ">>"))
        self.graph_tab.setTabText(self.graph_tab.indexOf(self.full_time_tab), _translate("MainWindow", "Full Time Graph"))
        self.label_video_1.setText(_translate("MainWindow", "VIDEO 1"))
        self.next_video_1.setText(_translate("MainWindow", ">>"))
        self.label_video_2.setText(_translate("MainWindow", "VIDEO 2"))
        self.next_video_2.setText(_translate("MainWindow", ">>"))
        self.label_video_3.setText(_translate("MainWindow", "VIDEO 3"))
        self.next_video_3.setText(_translate("MainWindow", ">>"))
        self.label_video_4.setText(_translate("MainWindow", "VIDEO 4"))
        self.next_video_4.setText(_translate("MainWindow", ">>"))
        self.graph_tab.setTabText(self.graph_tab.indexOf(self.partition_tab), _translate("MainWindow", "Partition Graph"))
        self.label_rtc.setText(_translate("MainWindow", "Real Time Value"))
        self.var_gsr.setText(_translate("MainWindow", "0.0005"))
        self.label_gsr.setText(_translate("MainWindow", "GSR(uS):"))
        self.label_interval.setText(_translate("MainWindow", "R-R(ms):"))
        self.var_interval.setText(_translate("MainWindow", "720"))
        self.label_hrv.setText(_translate("MainWindow", "HRV(ms):"))
        self.var_hrv.setText(_translate("MainWindow", "720"))
        self.label_comment.setText(_translate("MainWindow", "Comment"))
        self.label_history.setText(_translate("MainWindow", "History"))
        self.button_start.setText(_translate("MainWindow", "START"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_File.setText(_translate("MainWindow", "New File"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionLoad_File.setText(_translate("MainWindow", "Load File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
